### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by abarazal** [j-easy/easy-flows#11]
Since last commit was on 5 Nov 2017, is this project no longer maintained?

**Comment by benas** [comment]
No, this project is still maintained. The reason for that is that there are no bugs reported since the last release (all open issues are nice to have features). So either the software is rock-solid and bug-free, or no one is using it 🙃 

More seriously, I was busy releasing easy-rules and easy-random the last couple of months, and now I'm working on easy-batch (v5.3 was released just [yesterday](https://github.com/j-easy/easy-batch/releases/tag/easybatch-5.3.0)). Easy flows and others are next in the pipe.
