### ISSUE TITLE
Alternative implementation of ParallelFlow using CompletableFuture instead of Future

### ISSUE THREAD

**Issue by arunav-b** [j-easy/easy-flows#21]
Instead of using Future and poll for the completion of the same using isDone(), an alternative way of doing this would be to use CompletableFuture.supplyAsync() and thenAccept the WorkReports once they are completed. To check for the completion of all the Works we can use CompletableFuture.all method. 

I can fork and submit my code on this. You can take a look and let me know your views on it.

On a side note, I have already submitted an Issue for an asyncFlow (https://github.com/j-easy/easy-flows/issues/20). Do you want me to fork these changes separately or I can push it in a single fork ?

**Comment by benas** [comment]
Since we have to wait for all reports anyway, all we need is actually a call to `ExecutorService#submitAll`. No need to submit futures separately and poll for their result manually (either synchronously as currently done or asynchronously using `CompletableFuture` as suggested here).

I'm closing this issue since the `ExecutorService#invokeAll` approach has been implemented in deff6a9ebdade23fd5cd4428dac6009472a159f1. Thank you for your suggestion!
