### ISSUE TITLE
Use of MVEL / SpEL in easy-flows

### ISSUE THREAD

**Issue by Yogesn** [j-easy/easy-flows#23]
Please include Expression language support into the easy-flows.

Is there a way to link easy-rules in the easy-flows framework?

Such that the workflow should be defined using easy-flows and the intermediate conditions have to be defined through easy-rules (MVEL / SpEL)?

**Comment by benas** [comment]
There is no plan in the short term for such an integration. Easy flows is in an early stage and APIs are not stable yet, so it's too early to start working on something like that. Moreover, this kind of integration should be done outside of easy-flows and easy-rules projects. I see it as a separate module that glues things together.

For this reason, I'm closing this issue since anyone interested can develop this module in a separate repo.
